name: Nix Powered Tests

on:
  pull_request: {}
  push:
    branches:
    - main
    - master

jobs:
  rspec:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
    - run: |
        nix develop -c bash<<SH
          bundle install
          bundle exec rspec
        SH
